# -*- coding: utf-8 -*-
"""20251127.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6H3fCPHqe0OgaJOhX85MyB94kLj41jA
"""

# 한밭대 산업경영공학과 4학년 취업 역량 진단 프로그램

# 직무별 필요한 스킬셋 정의
job_skills = {
    "데이터분석": {
        "Python", "Pandas", "Numpy", "통계분석", "Machine Learning",
        "데이터전처리", "시각화", "SQL", "산업데이터해석"
    },
    "생산관리": {
        "생산자동화", "공정관리", "설비관리", "스케줄링",
        "스마트팩토리", "품질관리", "6시그마", "안전관리", "ERP"
    },
    "물류/SCM": {
        "SCM", "물류최적화", "재고관리", "글로벌물류",
        "수요예측", "물류자동화", "데이터분석"
    }
}

# 학습 난이도별 추천 자료
learning_resources = {
    "Python": "패스트캠퍼스 ‘파이썬 데이터분석’",
    "Pandas": "유튜브 나도코딩 Pandas",
    "통계분석": "기초통계(전공 교재 + ADsP)",
    "Machine Learning": "혼자 공부하는 머신러닝",
    "SQL": "생활코딩 SQL",
    "생산자동화": "4학년 ‘생산자동화’ 강의 노트",
    "공정관리": "전공 ‘생산운영관리’",
    "스마트팩토리": "스마트팩토리 실무 교재",
    "6시그마": "GB 교재 + 제조품질 유튜브",
    "ERP": "ERP 정보관리사 기출",
    "SCM": "고급SCM 강의 자료",
    "글로벌물류": "물류관리사 교재",
    "수요예측": "시계열 기반 수요예측 자료"
}

# 우선순위 계산 규칙
def priority(level):
    if level >= 3:
        return "상"
    elif level == 2:
        return "중"
    else:
        return "하"

print("=== 취업 역량 진단 & 학습 로드맵 생성기 (산업경영공학과 4학년 전용) ===")
while True:
    job = input("희망 직무를 입력하세요 (데이터분석 / 생산관리 / 물류/SCM): ")
    if job in job_skills:
        break
    print("❌ 직무 입력 오류: 제시된 세 가지 중 하나를 정확히 입력하세요.\n")

# 사용자 기술 입력
user_input = input("당신이 보유한 기술을 쉼표로 구분해 입력하세요: ")
user_skills = {t.strip() for t in user_input.split(",")}

# 부족 스킬 계산
required = job_skills[job]
missing = required - user_skills

print("\n[1] 필요 기술 목록")
print(required)

print("\n[2] 보유 기술 목록")
print(user_skills)

print("\n[3] 부족한 기술")
print(missing if missing else "없음 (매우 우수!)")

# 우선순위 설정 (난이도 + 직무 핵심도 기반 단순화)
print("\n[4] 부족 기술 우선순위")
priority_map = {}

for skill in missing:
    # 핵심 기술이면 상, 중간 기술이면 중, 나머지는 하
    if skill in {"Machine Learning", "스마트팩토리", "SCM"}:
        priority_map[skill] = "상"
    elif skill in {"SQL", "공정관리", "수요예측"}:
        priority_map[skill] = "중"
    else:
        priority_map[skill] = "하"

for s, p in priority_map.items():
    print(f"- {s}: 우선순위 {p}")

# 로드맵 생성
print("\n[5] 맞춤 학습 로드맵")

for s in missing:
    resource = learning_resources.get(s, "관련 자료 직접 검색 필요")
    print(f"● {s} → 추천자료: {resource}")

print("\n=== 분석 완료: 이 로드맵을 기준으로 4학년 진로 준비 가능 ===")

